version: "3"
services:
  mysql:
    image: mysql
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 11000:3306
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "8080:80"
    networks:
      - laravel-network
    volumes:
      - .:/code
      - ./public/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    image: devilbox/php-fpm:8.1-work
    container_name: php-fpm
    working_dir: /code
    networks:
      - laravel-network
      - system-network
    volumes:
      - .:/code

volumes:
  mysql-volume:

networks:
  laravel-network:
  system-network:
    external: true
