version: "3"
services:
  node:
    image: node:14.15
    container_name: node
    working_dir: /code/server
    environment:
      - NODE_ENV=local
    volumes:
      - ./:/code
    command: "tail -f /dev/null"
    ports:
      - 8081:8081
    networks:
      - node-network
      - system-network

  mysql:
    image: mysql
    container_name: node-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: node
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 11001:3306
    networks:
      - node-network

volumes:
  mysql-volume:

networks:
  node-network:
  system-network:
    external: true